package StudentDatabase;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;
import java.nio.file.Files;
import java.util.List;
import java.util.Scanner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

class FileHandlerTest {

    StudentFactory studentFactory = new StudentFactory("Some valid value");
    FileHandler fileHandler = new FileHandler(studentFactory);

    @Test
    void inputFromFile() {

        //the inputfromfile test creates three students, adds a topic to one student, awards a prize
        //to another student and writes the student data to a file and asserts that the file has the expected data

        studentFactory.createStudent(new String[]{"S", "2390568", "Malorn", "Dreamsong", "Balance"});
        studentFactory.createStudent(new String[]{"S", "1212121", "Scarlet", "Shadowrider", "Death"});
        studentFactory.createStudent(new String[]{"S", "9090909", "Amber", "Brightspark", "Storm"});

        try {
            try {
                studentFactory.addTopicToStudent(new String[]{"R", "2390568", "Fire"});
            } catch (Exception e) {
                fail("Exception occurred while adding a topic: " + e.getMessage());
            }
            try {
                studentFactory.awardPrize(new String[]{"P", "1212121", "PvP Champion"});
            } catch (Exception e) {
                fail("Exception occurred while awarding a prize: " + e.getMessage());
            }

            File tempFile = File.createTempFile("student_data.txt", null);
            tempFile.deleteOnExit();
            fileHandler.writeToFile(studentFactory);
            List<String> lines = Files.readAllLines(tempFile.toPath());
            assertEquals("S,2390568,Malorn,Dreamsong,Balance", lines.get(0));
            assertEquals("S,1212121,Scarlet,Shadowrider,Death", lines.get(1));
            assertEquals("S,9090909,Amber,Brightspark,Storm", lines.get(2));
            assertEquals("R,2390568,Fire", lines.get(3));
            assertEquals("P,1212121,PvP Champion", lines.get(4));
        } catch (Exception e) {
            fail("Exception occurred: " + e.getMessage());
        }

    }

    @Test
    void writeToFile() {

        //the writetofile test creates a temporary file and captures the output generated by writetofile()
        //it than reads the content from the temporary file and compares it with the
        //captured output to make sure that they are the same

        try {
            File tempFile = File.createTempFile("student_data.txt", null);
            tempFile.deleteOnExit();
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            PrintStream printStream = new PrintStream(outputStream);
            System.setOut(printStream);
            StudentFactory studentFactory = new StudentFactory("FactoryName");
            FileHandler fileHandler = new FileHandler(studentFactory);
            fileHandler.writeToFile(studentFactory);
            System.setOut(System.out);
            String actualContent = outputStream.toString().trim();
            StringBuilder expectedContentBuilder = new StringBuilder();
            Scanner scanner = new Scanner(tempFile);

            while (scanner.hasNextLine()) {
                expectedContentBuilder.append(scanner.nextLine()).append("\n");
            }
            String expectedContent = expectedContentBuilder.toString().trim();
            assertEquals(expectedContent, actualContent);
        } catch (Exception e) {
            fail("Exception occurred: " + e.getMessage());
        }

    }
}